// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PesquisaPCS.Models;

namespace PesquisaPCS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210513215903_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PesquisaPCS.Models.Agrotoxico", b =>
                {
                    b.Property<int>("Idagrotoxico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome_agrotoxico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Principio_ativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_agrotoxico")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idagrotoxico");

                    b.ToTable("Agrotoxicos");
                });

            modelBuilder.Entity("PesquisaPCS.Models.Amostra", b =>
                {
                    b.Property<int>("IdAmostra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aborto_espontaneo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adoeceu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Agitacao_irritabilidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alt_discretizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alteracao_snervoso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ambulatorio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aparelho_auditivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aparelho_digestorio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aparelho_respiratorio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aparelho_urinario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Arritmia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ast_discretizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Azia_queimacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bota_protecao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cafe_mldia_discretizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Catarro_escarro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ch_e_discretizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ch_p_discretizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ch_t_discretizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Circunferencia_abdominal_discretizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classe_produto1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classe_produto2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classe_produto3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colicas_dorbarriga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contato_praguicida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Creatinina_discretizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dc_irritativa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dc_sensibilizante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diarreia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dificuldade_engravidar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Digestorio_cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Digestorio_cancerfamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diminuicao_audicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diminuicao_urina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doenca_cardiovascular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dor_cabeca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dor_estomago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eda_regiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipamento_protecao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etilismo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etilismo_anterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etilismo_atual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exposicao_raiox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Falta_dear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Familia_cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Filho_maformacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Forma_aplicacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formigamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fraqueza_muscular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Funcao_trabalho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gestante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Glandular_cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Glandular_cancerfamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habito_alimentar_discretizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hipertensao_arterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hipotensao_arterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idade_discretizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idpaciente")
                        .HasColumnType("int");

                    b.Property<string>("Imc_discretizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Incoordenacao_motora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingestao_cafe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Internado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Irritacao_ocular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Irritaçao_nasal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Luvas_protecao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mascara_protecao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicamento_continuo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nauseas_enjoo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nvezes_adoeceu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nvezes_internado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oculos_protecao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pele_mucosa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pele_osso_sangue_cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pele_osso_sangue_cancerfamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protetor_auricular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quando_internado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quandodias_exposicao_discretizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relacao_trabalho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remedio_micose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reprodutor_cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reprodutor_cancerfamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Respiratorio_cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Respiratorio_cancerfamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roupa_protecao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Sigla_diagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Snc_cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Snc_cancerfamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabagismo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabagismo_anterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabagismo_atual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tem_filhos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tempo_contato_discretizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teve_cancerv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tosse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tremedeira")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tremor_muscular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ultimo_contato_discretizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Urinaescura_sangue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vertigens_tonturas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Via_exposicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Visãoturva_embacada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vomito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Y_gt_discretizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zumbido")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAmostra");

                    b.ToTable("Amostras");
                });

            modelBuilder.Entity("PesquisaPCS.Models.Diagnostico", b =>
                {
                    b.Property<int>("Iddiagnostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao_diagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla_diagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Iddiagnostico");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("PesquisaPCS.Models.Ficha", b =>
                {
                    b.Property<int>("Idficha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aborto_espontaneo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adoeceu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Agitacao_irritabilidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Alt")
                        .HasColumnType("float");

                    b.Property<string>("Alteracao_snervoso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ambulatorio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aparelho_auditivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aparelho_digestorio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aparelho_respiratorio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aparelho_urinario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Arritmia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ast")
                        .HasColumnType("float");

                    b.Property<string>("Azia_queimacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bota_protecao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cafe_mldia")
                        .HasColumnType("float");

                    b.Property<string>("Catarro_escarro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ch_e")
                        .HasColumnType("float");

                    b.Property<double>("Ch_p")
                        .HasColumnType("float");

                    b.Property<double>("Ch_t")
                        .HasColumnType("float");

                    b.Property<int>("Circunferencia_abdominal")
                        .HasColumnType("int");

                    b.Property<string>("Colicas_dorbarriga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contato_praguicida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Creatinina")
                        .HasColumnType("float");

                    b.Property<string>("Cultura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dc_irritativa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dc_sensibilizante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diarreia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dificuldade_engravidar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Digestorio_cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Digestorio_cancerfamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diminuicao_audicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diminuicao_urina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doenca_cardiovascular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dor_cabeca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dor_estomago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eda_regiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipamento_protecao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etilismo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etilismo_anterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etilismo_atual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exposicao_raiox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Falta_dear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Familia_cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Filho_maformacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Forma_aplicacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formigamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fraqueza_muscular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Funcao_trabalho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gestante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Glandular_cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Glandular_cancerfamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Habito_alimentar")
                        .HasColumnType("float");

                    b.Property<string>("Hipertensao_arterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hipotensao_arterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<int>("Iddiagnostico")
                        .HasColumnType("int");

                    b.Property<int>("Idmunicipio_trabalha")
                        .HasColumnType("int");

                    b.Property<int>("Idpaciente")
                        .HasColumnType("int");

                    b.Property<double>("Imc")
                        .HasColumnType("float");

                    b.Property<string>("Incoordenacao_motora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingestao_cafe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Internado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Irritacao_ocular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Irritaçao_nasal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Luvas_protecao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mascara_protecao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicamento_continuo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MunicipioIdmunicipio")
                        .HasColumnType("int");

                    b.Property<string>("Nauseas_enjoo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_remedio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nvezes_adoeceu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nvezes_internado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oculos_protecao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pele_mucosa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pele_osso_sangue_cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pele_osso_sangue_cancerfamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protetor_auricular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quando_internado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quandodias_exposicao")
                        .HasColumnType("int");

                    b.Property<string>("Relacao_trabalho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remedio_micose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reprodutor_cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reprodutor_cancerfamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Respiratorio_cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Respiratorio_cancerfamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roupa_protecao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Snc_cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Snc_cancerfamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabagismo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabagismo_anterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabagismo_atual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tem_filhos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tempo_contato")
                        .HasColumnType("int");

                    b.Property<string>("Teve_cancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tosse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tremedeira")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tremor_muscular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ultimo_contato")
                        .HasColumnType("int");

                    b.Property<string>("Urinaescura_sangue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vertigens_tonturas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Via_exposicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Visãoturva_embacada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vomito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Y_gt")
                        .HasColumnType("float");

                    b.Property<string>("Zumbido")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idficha");

                    b.HasIndex("MunicipioIdmunicipio");

                    b.ToTable("Fichas");
                });

            modelBuilder.Entity("PesquisaPCS.Models.Ficha_Agro", b =>
                {
                    b.Property<int>("Idficha_agro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Idficha")
                        .HasColumnType("int");

                    b.Property<int>("Idproduto")
                        .HasColumnType("int");

                    b.HasKey("Idficha_agro");

                    b.ToTable("Fichas_Agro");
                });

            modelBuilder.Entity("PesquisaPCS.Models.Municipio", b =>
                {
                    b.Property<int>("Idmunicipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome_municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PacienteIdpaciente")
                        .HasColumnType("int");

                    b.HasKey("Idmunicipio");

                    b.HasIndex("PacienteIdpaciente");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("PesquisaPCS.Models.Paciente", b =>
                {
                    b.Property<int>("Idpaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data_nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Escolaridade")
                        .HasColumnType("int");

                    b.Property<int>("Idmunicipio_residencia")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zona_residencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idpaciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("PesquisaPCS.Models.Ficha", b =>
                {
                    b.HasOne("PesquisaPCS.Models.Municipio", null)
                        .WithMany("Fichas")
                        .HasForeignKey("MunicipioIdmunicipio");
                });

            modelBuilder.Entity("PesquisaPCS.Models.Municipio", b =>
                {
                    b.HasOne("PesquisaPCS.Models.Paciente", null)
                        .WithMany("Municipios")
                        .HasForeignKey("PacienteIdpaciente");
                });
#pragma warning restore 612, 618
        }
    }
}
